export const totalVendasAnualPorCategoria = {
    "2015": [
        { "name": "Total Electronic Shopping", "value": 433692 },
        { "name": "Books and magazines", "value": 12583 },
        { "name": "Clothing and clothing accessories", "value": 58188 },
        { "name": "Computer hardware", "value": 0 },
        { "name": "Computer software", "value": 0 },
        { "name": "Drugs, health and beauty aids", "value": 0 },
        { "name": "Electronics and appliances", "value": 30016 },
        { "name": "Food, beer, and wine", "value": 9841 },
        { "name": "Furniture and home furnishings", "value": 32369 },
        { "name": "Music and videos", "value": 0 },
        { "name": "Office equipment and supplies", "value": 10613 },
        { "name": "Sporting Goods", "value": 13104 },
        { "name": "Toys, hobby goods, and games", "value": 12110 },
        { "name": "Other merchandise²", "value": 68378 },        
        { "name": "Nonmerchandise receipts³", "value": 29153 }        
    ],
	"2014": [
        { "name": "Total Electronic Shopping", "value": 386065 },
        { "name": "Books and magazines", "value": 11879 },
        { "name": "Clothing and clothing accessories", "value": 53751 },
        { "name": "Computer hardware", "value": 29527 },
        { "name": "Computer software", "value": 9594 },
        { "name": "Drugs, health and beauty aids", "value": 93586 },
        { "name": "Electronics and appliances", "value": 28158 },
        { "name": "Food, beer, and wine", "value": 8636 },
        { "name": "Furniture and home furnishings", "value": 26599 },
        { "name": "Music and videos", "value": 0 },
        { "name": "Office equipment and supplies", "value": 0 },
        { "name": "Sporting Goods", "value": 10910 },
        { "name": "Toys, hobby goods, and games", "value": 10623 },
        { "name": "Other merchandise²", "value": 55104 },        
        { "name": "Nonmerchandise receipts³", "value": 25500 }        
    ],
	"2013": [
        { "name": "Total Electronic Shopping", "value": 350487 },
        { "name": "Books and magazines", "value": 11444 },
        { "name": "Clothing and clothing accessories", "value": 46681 },
        { "name": "Computer hardware", "value": 26981 },
        { "name": "Computer software", "value": 8329 },
        { "name": "Drugs, health and beauty aids", "value": 91001 },
        { "name": "Electronics and appliances", "value": 27541 },
        { "name": "Food, beer, and wine", "value": 7783 },
        { "name": "Furniture and home furnishings", "value": 22856 },
        { "name": "Music and videos", "value": 11263 },
        { "name": "Office equipment and supplies", "value": 8042 },
        { "name": "Sporting Goods", "value": 9914 },
        { "name": "Toys, hobby goods, and games", "value": 9125 },
        { "name": "Other merchandise²", "value": 47981 },        
        { "name": "Nonmerchandise receipts³", "value": 21546 }        
    ],
	"2012": [
        { "name": "Total Electronic Shopping", "value": 328655 },
        { "name": "Books and magazines", "value": 10991 },
        { "name": "Clothing and clothing accessories", "value": 40451 },
        { "name": "Computer hardware", "value": 25640 },
        { "name": "Computer software", "value": 8093 },
        { "name": "Drugs, health and beauty aids", "value": 90714 },
        { "name": "Electronics and appliances", "value": 26573 },
        { "name": "Food, beer, and wine", "value": 7070 },
        { "name": "Furniture and home furnishings", "value": 19420 },
        { "name": "Music and videos", "value": 9914 },
        { "name": "Office equipment and supplies", "value": 8579 },
        { "name": "Sporting Goods", "value": 8506 },
        { "name": "Toys, hobby goods, and games", "value": 7801 },
        { "name": "Other merchandise²", "value": 44679 },        
        { "name": "Nonmerchandise receipts³", "value": 20224 }        
    ],
	"2011": [
        { "name": "Total Electronic Shopping", "value": 294697 },
        { "name": "Books and magazines", "value": 10160 },
        { "name": "Clothing and clothing accessories", "value": 35137 },
        { "name": "Computer hardware", "value": 24948 },
        { "name": "Computer software", "value": 6854 },
        { "name": "Drugs, health and beauty aids", "value": 82424 },
        { "name": "Electronics and appliances", "value": 24622 },
        { "name": "Food, beer, and wine", "value": 5985 },
        { "name": "Furniture and home furnishings", "value": 16900 },
        { "name": "Music and videos", "value": 8225 },
        { "name": "Office equipment and supplies", "value": 8136 },
        { "name": "Sporting Goods", "value": 6982 },
        { "name": "Toys, hobby goods, and games", "value": 6794 },
        { "name": "Other merchandise²", "value": 39998 },        
        { "name": "Nonmerchandise receipts³", "value": 17532 }        
    ],
	"2010": [
        { "name": "Total Electronic Shopping", "value": 263488 },
        { "name": "Books and magazines", "value": 8860 },
        { "name": "Clothing and clothing accessories", "value": 31388 },
        { "name": "Computer hardware", "value": 22420 },
        { "name": "Computer software", "value": 5834 },
        { "name": "Drugs, health and beauty aids", "value": 75318 },
        { "name": "Electronics and appliances", "value": 21732 },
        { "name": "Food, beer, and wine", "value": 5267 },
        { "name": "Furniture and home furnishings", "value": 14518 },
        { "name": "Music and videos", "value": 0 },
        { "name": "Office equipment and supplies", "value": 7822 },
        { "name": "Sporting Goods", "value": 6437 },
        { "name": "Toys, hobby goods, and games", "value": 6022 },
        { "name": "Other merchandise²", "value": 35221 },        
        { "name": "Nonmerchandise receipts³", "value": 15548 }        
    ],
	"2009": [
        { "name": "Total Electronic Shopping", "value": 235625 },
        { "name": "Books and magazines", "value": 7569 },
        { "name": "Clothing and clothing accessories", "value": 27300 },
        { "name": "Computer hardware", "value": 20141 },
        { "name": "Computer software", "value": 5432 },
        { "name": "Drugs, health and beauty aids", "value": 69164 },
        { "name": "Electronics and appliances", "value": 18798 },
        { "name": "Food, beer, and wine", "value": 4824 },
        { "name": "Furniture and home furnishings", "value": 12759 },
        { "name": "Music and videos", "value": 6107 },
        { "name": "Office equipment and supplies", "value": 7730 },
        { "name": "Sporting Goods", "value": 6058 },
        { "name": "Toys, hobby goods, and games", "value": 5384 },
        { "name": "Other merchandise²", "value": 30895 },        
        { "name": "Nonmerchandise receipts³", "value": 13464 }        
    ],
	"2008": [
        { "name": "Total Electronic Shopping", "value": 229242 },
        { "name": "Books and magazines", "value": 7642 },
        { "name": "Clothing and clothing accessories", "value": 25545 },
        { "name": "Computer hardware", "value": 20923 },
        { "name": "Computer software", "value": 4906 },
        { "name": "Drugs, health and beauty aids", "value": 64783 },
        { "name": "Electronics and appliances", "value": 17457 },
        { "name": "Food, beer, and wine", "value": 4891 },
        { "name": "Furniture and home furnishings", "value": 13303 },
        { "name": "Music and videos", "value": 5321 },
        { "name": "Office equipment and supplies", "value": 8183 },
        { "name": "Sporting Goods", "value": 5823 },
        { "name": "Toys, hobby goods, and games", "value": 5667 },
        { "name": "Other merchandise²", "value": 31314 },        
        { "name": "Nonmerchandise receipts³", "value": 13483 }        
    ],
	"2007": [
        { "name": "Total Electronic Shopping", "value": 223681 },
        { "name": "Books and magazines", "value": 7185 },
        { "name": "Clothing and clothing accessories", "value": 24314 },
        { "name": "Computer hardware", "value": 22855 },
        { "name": "Computer software", "value": 4597 },
        { "name": "Drugs, health and beauty aids", "value": 61859 },
        { "name": "Electronics and appliances", "value": 15991 },
        { "name": "Food, beer, and wine", "value": 5132 },
        { "name": "Furniture and home furnishings", "value": 13444 },
        { "name": "Music and videos", "value": 4638 },
        { "name": "Office equipment and supplies", "value": 8097 },
        { "name": "Sporting Goods", "value": 5567 },
        { "name": "Toys, hobby goods, and games", "value": 5414 },
        { "name": "Other merchandise²", "value": 31145 },        
        { "name": "Nonmerchandise receipts³", "value": 13443 }        
    ],
	"2006": [
        { "name": "Total Electronic Shopping", "value": 202251 },
        { "name": "Books and magazines", "value": 5983 },
        { "name": "Clothing and clothing accessories", "value": 21075 },
        { "name": "Computer hardware", "value": 20176 },
        { "name": "Computer software", "value": 3845 },
        { "name": "Drugs, health and beauty aids", "value": 63305 },
        { "name": "Electronics and appliances", "value": 13925 },
        { "name": "Food, beer, and wine", "value": 4213 },
        { "name": "Furniture and home furnishings", "value": 12028 },
        { "name": "Music and videos", "value": 3869 },
        { "name": "Office equipment and supplies", "value": 6959 },
        { "name": "Sporting Goods", "value": 4502 },
        { "name": "Toys, hobby goods, and games", "value": 4638 },
        { "name": "Other merchandise²", "value": 26416 },        
        { "name": "Nonmerchandise receipts³", "value": 11320 }        
    ],
	"2005": [
        { "name": "Total Electronic Shopping", "value": 175900 },
        { "name": "Books and magazines", "value": 5438 },
        { "name": "Clothing and clothing accessories", "value": 18562 },
        { "name": "Computer hardware", "value": 20601 },
        { "name": "Computer software", "value": 3706 },
        { "name": "Drugs, health and beauty aids", "value": 49810 },
        { "name": "Electronics and appliances", "value": 10953 },
        { "name": "Food, beer, and wine", "value": 3406 },
        { "name": "Furniture and home furnishings", "value": 10576 },
        { "name": "Music and videos", "value": 3412 },
        { "name": "Office equipment and supplies", "value": 6112 },
        { "name": "Sporting Goods", "value": 4179 },
        { "name": "Toys, hobby goods, and games", "value": 4649 },
        { "name": "Other merchandise²", "value": 25169 },        
        { "name": "Nonmerchandise receipts³", "value": 9327 }        
    ],
	"2004": [
        { "name": "Total Electronic Shopping", "value": 154157 },
        { "name": "Books and magazines", "value": 4930 },
        { "name": "Clothing and clothing accessories", "value": 15681 },
        { "name": "Computer hardware", "value": 20277 },
        { "name": "Computer software", "value": 3089 },
        { "name": "Drugs, health and beauty aids", "value": 43338 },
        { "name": "Electronics and appliances", "value": 9277 },
        { "name": "Food, beer, and wine", "value": 2520 },
        { "name": "Furniture and home furnishings", "value": 8515 },
        { "name": "Music and videos", "value": 3591 },
        { "name": "Office equipment and supplies", "value": 0 },
        { "name": "Sporting Goods", "value": 3579 },
        { "name": "Toys, hobby goods, and games", "value": 4133 },
        { "name": "Other merchandise²", "value": 21632 },        
        { "name": "Nonmerchandise receipts³", "value": 8242 }        
    ],
	"2003": [
        { "name": "Total Electronic Shopping", "value": 134304 },
        { "name": "Books and magazines", "value": 4446 },
        { "name": "Clothing and clothing accessories", "value": 14497 },
        { "name": "Computer hardware", "value": 18366 },
        { "name": "Computer software", "value": 2930 },
        { "name": "Drugs, health and beauty aids", "value": 34783 },
        { "name": "Electronics and appliances", "value": 7151 },
        { "name": "Food, beer, and wine", "value": 2172 },
        { "name": "Furniture and home furnishings", "value": 8057 },
        { "name": "Music and videos", "value": 3473 },
        { "name": "Office equipment and supplies", "value": 5194 },
        { "name": "Sporting Goods", "value": 3053 },
        { "name": "Toys, hobby goods, and games", "value": 4049 },
        { "name": "Other merchandise²", "value": 19357 },        
        { "name": "Nonmerchandise receipts³", "value": 6776 }        
    ],
	"2002": [
        { "name": "Total Electronic Shopping", "value": 122214 },
        { "name": "Books and magazines", "value": 4267 },
        { "name": "Clothing and clothing accessories", "value": 14477 },
        { "name": "Computer hardware", "value": 18718 },
        { "name": "Computer software", "value": 3661 },
        { "name": "Drugs, health and beauty aids", "value": 27471 },
        { "name": "Electronics and appliances", "value": 5520 },
        { "name": "Food, beer, and wine", "value": 2014 },
        { "name": "Furniture and home furnishings", "value": 7290 },
        { "name": "Music and videos", "value": 3902 },
        { "name": "Office equipment and supplies", "value": 5099 },
        { "name": "Sporting Goods", "value": 3073 },
        { "name": "Toys, hobby goods, and games", "value": 3775 },
        { "name": "Other merchandise²", "value": 17539 },        
        { "name": "Nonmerchandise receipts³", "value": 5408 }        
    ],
	"2001": [
        { "name": "Total Electronic Shopping", "value": 114749 },
        { "name": "Books and magazines", "value": 4137 },
        { "name": "Clothing and clothing accessories", "value": 15712 },
        { "name": "Computer hardware", "value": 21128 },
        { "name": "Computer software", "value": 3983 },
        { "name": "Drugs, health and beauty aids", "value": 19707 },
        { "name": "Electronics and appliances", "value": 4535 },
        { "name": "Food, beer, and wine", "value": 2037 },
        { "name": "Furniture and home furnishings", "value": 6696 },
        { "name": "Music and videos", "value": 4083 },
        { "name": "Office equipment and supplies", "value": 5740 },
        { "name": "Sporting Goods", "value": 1906 },
        { "name": "Toys, hobby goods, and games", "value": 3138 },
        { "name": "Other merchandise²", "value": 17676 },        
        { "name": "Nonmerchandise receipts³", "value": 4271 }        
    ],
	"2000": [
        { "name": "Total Electronic Shopping", "value": 113790 },
        { "name": "Books and magazines", "value": 4297 },
        { "name": "Clothing and clothing accessories", "value": 15415 },
        { "name": "Computer hardware", "value": 27221 },
        { "name": "Computer software", "value": 3706 },
        { "name": "Drugs, health and beauty aids", "value": 15557 },
        { "name": "Electronics and appliances", "value": 3641 },
        { "name": "Food, beer, and wine", "value": 1960 },
        { "name": "Furniture and home furnishings", "value": 6556 },
        { "name": "Music and videos", "value": 4433 },
        { "name": "Office equipment and supplies", "value": 6600 },
        { "name": "Sporting Goods", "value": 1794 },
        { "name": "Toys, hobby goods, and games", "value": 3174 },
        { "name": "Other merchandise²", "value": 16249 },        
        { "name": "Nonmerchandise receipts³", "value": 3187 }        
    ],
	"1999": [
        { "name": "Total Electronic Shopping", "value": 94282 },
        { "name": "Books and magazines", "value": 3434 },
        { "name": "Clothing and clothing accessories", "value": 13535 },
        { "name": "Computer hardware", "value": 23846 },
        { "name": "Computer software", "value": 2809 },
        { "name": "Drugs, health and beauty aids", "value": 11557 },
        { "name": "Electronics and appliances", "value": 2709 },
        { "name": "Food, beer, and wine", "value": 1429 },
        { "name": "Furniture and home furnishings", "value": 5822 },
        { "name": "Music and videos", "value": 4250 },
        { "name": "Office equipment and supplies", "value": 7284 },
        { "name": "Sporting Goods", "value": 0 },
        { "name": "Toys, hobby goods, and games", "value": 2162 },
        { "name": "Other merchandise²", "value": 0 },        
        { "name": "Nonmerchandise receipts³", "value": 1126 }        
    ]	
};