export const totalEcommerceAnualPorCategoria = {
    "2015": [
        { "name": "Total Electronic Shopping", "value": 294809 },
        { "name": "Books and magazines", "value": 11648 },
        { "name": "Clothing and clothing accessories", "value": 52128 },
        { "name": "Computer hardware", "value": 17459 },
        { "name": "Computer software", "value": 0 },
        { "name": "Drugs, health and beauty aids", "value": 21469 },
        { "name": "Electronics and appliances", "value": 26050 },
        { "name": "Food, beer, and wine", "value": 7579 },
        { "name": "Furniture and home furnishings", "value": 28883 },
        { "name": "Music and videos", "value": 0 },
        { "name": "Office equipment and supplies", "value": 9236 },
        { "name": "Sporting Goods", "value": 11681 },
        { "name": "Toys, hobby goods, and games", "value": 10682 },
        { "name": "Other merchandise²", "value": 52893 },        
        { "name": "Nonmerchandise receipts³", "value": 26374 }        
    ],
	"2014*": [
        { "name": "Total Electronic Shopping", "value": 256269 },
        { "name": "Books and magazines", "value": 10828 },
        { "name": "Clothing and clothing accessories", "value": 46830 },
        { "name": "Computer hardware", "value": 16884 },
        { "name": "Computer software", "value": 6491 },
        { "name": "Drugs, health and beauty aids", "value": 19112 },
        { "name": "Electronics and appliances", "value": 24234 },
        { "name": "Food, beer, and wine", "value": 6349 },
        { "name": "Furniture and home furnishings", "value": 23311 },
        { "name": "Music and videos", "value": 0 },
        { "name": "Office equipment and supplies", "value": 0 },
        { "name": "Sporting Goods", "value": 9437 },
        { "name": "Toys, hobby goods, and games", "value": 8997 },
        { "name": "Other merchandise²", "value": 41543 },        
        { "name": "Nonmerchandise receipts³", "value": 22317 }        
    ],
	"2013*": [
        { "name": "Total Electronic Shopping", "value": 221587 },
        { "name": "Books and magazines", "value": 10249 },
        { "name": "Clothing and clothing accessories", "value": 40198 },
        { "name": "Computer hardware", "value": 15330 },
        { "name": "Computer software", "value": 5425 },
        { "name": "Drugs, health and beauty aids", "value": 17456 },
        { "name": "Electronics and appliances", "value": 23727 },
        { "name": "Food, beer, and wine", "value": 5267 },
        { "name": "Furniture and home furnishings", "value": 19588 },
        { "name": "Music and videos", "value": 10325 },
        { "name": "Office equipment and supplies", "value": 0 },
        { "name": "Sporting Goods", "value": 7927 },
        { "name": "Toys, hobby goods, and games", "value": 0 },
        { "name": "Other merchandise²", "value": 34491 },        
        { "name": "Nonmerchandise receipts³", "value": 17721 }        
    ],
	"2012*": [
        { "name": "Total Electronic Shopping", "value": 195477 },
        { "name": "Books and magazines", "value": 9778 },
        { "name": "Clothing and clothing accessories", "value": 33614 },
        { "name": "Computer hardware", "value": 14240 },
        { "name": "Computer software", "value": 5425 },
        { "name": "Drugs, health and beauty aids", "value": 14612 },
        { "name": "Electronics and appliances", "value": 22580 },
        { "name": "Food, beer, and wine", "value": 4934 },
        { "name": "Furniture and home furnishings", "value": 15917 },
        { "name": "Music and videos", "value": 8964 },
        { "name": "Office equipment and supplies", "value": 6869 },
        { "name": "Sporting Goods", "value": 6356 },
        { "name": "Toys, hobby goods, and games", "value": 6094 },
        { "name": "Other merchandise²", "value": 30045 },        
        { "name": "Nonmerchandise receipts³", "value": 16052 }        
    ],
	"2011*": [
        { "name": "Total Electronic Shopping", "value": 168919 },
        { "name": "Books and magazines", "value": 8773 },
        { "name": "Clothing and clothing accessories", "value": 28196 },
        { "name": "Computer hardware", "value": 13973 },
        { "name": "Computer software", "value": 4493 },
        { "name": "Drugs, health and beauty aids", "value": 11845 },
        { "name": "Electronics and appliances", "value": 20975 },
        { "name": "Food, beer, and wine", "value": 3984 },
        { "name": "Furniture and home furnishings", "value": 13536 },
        { "name": "Music and videos", "value": 7241 },
        { "name": "Office equipment and supplies", "value": 6432 },
        { "name": "Sporting Goods", "value": 5103 },
        { "name": "Toys, hobby goods, and games", "value": 5260 },
        { "name": "Other merchandise²", "value": 25491 },        
        { "name": "Nonmerchandise receipts³", "value": 13617 }        
    ],
	"2010*": [
        { "name": "Total Electronic Shopping", "value": 143000 },
        { "name": "Books and magazines", "value": 7428 },
        { "name": "Clothing and clothing accessories", "value": 23480 },
        { "name": "Computer hardware", "value": 12080 },
        { "name": "Computer software", "value": 3676 },
        { "name": "Drugs, health and beauty aids", "value": 10952 },
        { "name": "Electronics and appliances", "value": 17861 },
        { "name": "Food, beer, and wine", "value": 3372 },
        { "name": "Furniture and home furnishings", "value": 11150 },
        { "name": "Music and videos", "value": 0 },
        { "name": "Office equipment and supplies", "value": 6009 },
        { "name": "Sporting Goods", "value": 4408 },
        { "name": "Toys, hobby goods, and games", "value": 4470 },
        { "name": "Other merchandise²", "value": 20851 },        
        { "name": "Nonmerchandise receipts³", "value": 11222 }        
    ],
	"2009": [
        { "name": "Total Electronic Shopping", "value": 121173 },
        { "name": "Books and magazines", "value": 6000 },
        { "name": "Clothing and clothing accessories", "value": 19725 },
        { "name": "Computer hardware", "value": 11223 },
        { "name": "Computer software", "value": 3440 },
        { "name": "Drugs, health and beauty aids", "value": 8865 },
        { "name": "Electronics and appliances", "value": 15087 },
        { "name": "Food, beer, and wine", "value": 2966 },
        { "name": "Furniture and home furnishings", "value": 9262 },
        { "name": "Music and videos", "value": 5064 },
        { "name": "Office equipment and supplies", "value": 5975 },
        { "name": "Sporting Goods", "value": 3945 },
        { "name": "Toys, hobby goods, and games", "value": 3639 },
        { "name": "Other merchandise²", "value": 16613 },
        { "name": "Nonmerchandise receipts³", "value": 9369 }        
    ],
	"2008": [
        { "name": "Total Electronic Shopping", "value": 114642 },
        { "name": "Books and magazines", "value": 5599 },
        { "name": "Clothing and clothing accessories", "value": 17637 },
        { "name": "Computer hardware", "value": 11394 },
        { "name": "Computer software", "value": 2887 },
        { "name": "Drugs, health and beauty aids", "value": 7586 },
        { "name": "Electronics and appliances", "value": 13670 },
        { "name": "Food, beer, and wine", "value": 3033 },
        { "name": "Furniture and home furnishings", "value": 9540 },
        { "name": "Music and videos", "value": 4208 },
        { "name": "Office equipment and supplies", "value": 6425 },
        { "name": "Sporting Goods", "value": 3535 },
        { "name": "Toys, hobby goods, and games", "value": 3445 },
        { "name": "Other merchandise²", "value": 16353 },        
        { "name": "Nonmerchandise receipts³", "value": 9330 }        
    ],
	"2007": [
        { "name": "Total Electronic Shopping", "value": 105467 },
        { "name": "Books and magazines", "value": 5370 },
        { "name": "Clothing and clothing accessories", "value": 16036 },
        { "name": "Computer hardware", "value": 11694 },
        { "name": "Computer software", "value": 2613 },
        { "name": "Drugs, health and beauty aids", "value": 6473 },
        { "name": "Electronics and appliances", "value": 11955 },
        { "name": "Food, beer, and wine", "value": 2996 },
        { "name": "Furniture and home furnishings", "value": 9061 },
        { "name": "Music and videos", "value": 3379 },
        { "name": "Office equipment and supplies", "value": 5922 },
        { "name": "Sporting Goods", "value": 3178 },
        { "name": "Toys, hobby goods, and games", "value": 3112 },
        { "name": "Other merchandise²", "value": 14739 },        
        { "name": "Nonmerchandise receipts³", "value": 8939 }        
    ],
	"2006": [
        { "name": "Total Electronic Shopping", "value": 85945 },
        { "name": "Books and magazines", "value": 3694 },
        { "name": "Clothing and clothing accessories", "value": 12887 },
        { "name": "Computer hardware", "value": 10373 },
        { "name": "Computer software", "value": 2023 },
        { "name": "Drugs, health and beauty aids", "value": 5416 },
        { "name": "Electronics and appliances", "value": 9938 },
        { "name": "Food, beer, and wine", "value": 2280 },
        { "name": "Furniture and home furnishings", "value": 7857 },
        { "name": "Music and videos", "value": 2605 },
        { "name": "Office equipment and supplies", "value": 4919 },
        { "name": "Sporting Goods", "value": 2402 },
        { "name": "Toys, hobby goods, and games", "value": 2536 },
        { "name": "Other merchandise²", "value": 11979 },        
        { "name": "Nonmerchandise receipts³", "value": 7036 }        
    ],
	"2005": [
        { "name": "Total Electronic Shopping", "value": 68114 },
        { "name": "Books and magazines", "value": 2903 },
        { "name": "Clothing and clothing accessories", "value": 9463 },
        { "name": "Computer hardware", "value": 9345 },
        { "name": "Computer software", "value": 1834 },
        { "name": "Drugs, health and beauty aids", "value": 4270 },
        { "name": "Electronics and appliances", "value": 8084 },
        { "name": "Food, beer, and wine", "value": 1608 },
        { "name": "Furniture and home furnishings", "value": 5620 },
        { "name": "Music and videos", "value": 1864 },
        { "name": "Office equipment and supplies", "value": 3852 },
        { "name": "Sporting Goods", "value": 1912 },
        { "name": "Toys, hobby goods, and games", "value": 2240 },
        { "name": "Other merchandise²", "value": 9838 },        
        { "name": "Nonmerchandise receipts³", "value": 5281 }        
    ],
	"2004": [
        { "name": "Total Electronic Shopping", "value": 52996 },
        { "name": "Books and magazines", "value": 2270 },
        { "name": "Clothing and clothing accessories", "value": 7054 },
        { "name": "Computer hardware", "value": 8006 },
        { "name": "Computer software", "value": 1456 },
        { "name": "Drugs, health and beauty aids", "value": 3574 },
        { "name": "Electronics and appliances", "value": 0 },
        { "name": "Food, beer, and wine", "value": 1030 },
        { "name": "Furniture and home furnishings", "value": 4023 },
        { "name": "Music and videos", "value": 1480 },
        { "name": "Office equipment and supplies", "value": 0 },
        { "name": "Sporting Goods", "value": 1430 },
        { "name": "Toys, hobby goods, and games", "value": 1758 },
        { "name": "Other merchandise²", "value": 7152 },        
        { "name": "Nonmerchandise receipts³", "value": 4379 }        
    ],
	"2003": [
        { "name": "Total Electronic Shopping", "value": 41962 },
        { "name": "Books and magazines", "value": 1994 },
        { "name": "Clothing and clothing accessories", "value": 5501 },
        { "name": "Computer hardware", "value": 6580 },
        { "name": "Computer software", "value": 1192 },
        { "name": "Drugs, health and beauty aids", "value": 2606 },
        { "name": "Electronics and appliances", "value": 4109 },
        { "name": "Food, beer, and wine", "value": 820 },
        { "name": "Furniture and home furnishings", "value": 3283 },
        { "name": "Music and videos", "value": 1384 },
        { "name": "Office equipment and supplies", "value": 2929 },
        { "name": "Sporting Goods", "value": 1155 },
        { "name": "Toys, hobby goods, and games", "value": 1610 },
        { "name": "Other merchandise²", "value": 5548 },        
        { "name": "Nonmerchandise receipts³", "value": 3251 }        
    ],
	"2002": [
        { "name": "Total Electronic Shopping", "value": 33764 },
        { "name": "Books and magazines", "value": 1787 },
        { "name": "Clothing and clothing accessories", "value": 4545 },
        { "name": "Computer hardware", "value": 6079 },
        { "name": "Computer software", "value": 1239 },
        { "name": "Drugs, health and beauty aids", "value": 1849 },
        { "name": "Electronics and appliances", "value": 2704 },
        { "name": "Food, beer, and wine", "value": 714 },
        { "name": "Furniture and home furnishings", "value": 2412 },
        { "name": "Music and videos", "value": 1352 },
        { "name": "Office equipment and supplies", "value": 2285 },
        { "name": "Sporting Goods", "value": 1028 },
        { "name": "Toys, hobby goods, and games", "value": 1259 },
        { "name": "Other merchandise²", "value": 4062 },        
        { "name": "Nonmerchandise receipts³", "value": 2449 }        
    ],
	"2001": [
        { "name": "Total Electronic Shopping", "value": 25892 },
        { "name": "Books and magazines", "value": 1644 },
        { "name": "Clothing and clothing accessories", "value": 3325 },
        { "name": "Computer hardware", "value": 5419 },
        { "name": "Computer software", "value": 1157 },
        { "name": "Drugs, health and beauty aids", "value": 1122 },
        { "name": "Electronics and appliances", "value": 1844 },
        { "name": "Food, beer, and wine", "value": 519 },
        { "name": "Furniture and home furnishings", "value": 1654 },
        { "name": "Music and videos", "value": 1211 },
        { "name": "Office equipment and supplies", "value": 1824 },
        { "name": "Sporting Goods", "value": 517 },
        { "name": "Toys, hobby goods, and games", "value": 896 },
        { "name": "Other merchandise²", "value": 2997 },        
        { "name": "Nonmerchandise receipts³", "value": 1763 }        
    ],
	"2000": [
        { "name": "Total Electronic Shopping", "value": 21221 },
        { "name": "Books and magazines", "value": 1759 },
        { "name": "Clothing and clothing accessories", "value": 2262 },
        { "name": "Computer hardware", "value": 6049 },
        { "name": "Computer software", "value": 1109 },
        { "name": "Drugs, health and beauty aids", "value": 701 },
        { "name": "Electronics and appliances", "value": 1128 },
        { "name": "Food, beer, and wine", "value": 591 },
        { "name": "Furniture and home furnishings", "value": 1006 },
        { "name": "Music and videos", "value": 1154 },
        { "name": "Office equipment and supplies", "value": 1375 },
        { "name": "Sporting Goods", "value": 409 },
        { "name": "Toys, hobby goods, and games", "value": 806 },
        { "name": "Other merchandise²", "value": 1866 },        
        { "name": "Nonmerchandise receipts³", "value": 1006 }        
    ],
	"1999": [
        { "name": "Total Electronic Shopping", "value": 11615 },
        { "name": "Books and magazines", "value": 1439 },
        { "name": "Clothing and clothing accessories", "value": 909 },
        { "name": "Computer hardware", "value": 4166 },
        { "name": "Computer software", "value": 755 },
        { "name": "Drugs, health and beauty aids", "value": 239 },
        { "name": "Electronics and appliances", "value": 504 },
        { "name": "Food, beer, and wine", "value": 235 },
        { "name": "Furniture and home furnishings", "value": 350 },
        { "name": "Music and videos", "value": 762 },
        { "name": "Office equipment and supplies", "value": 592 },
        { "name": "Sporting Goods", "value": 0 },
        { "name": "Toys, hobby goods, and games", "value": 383 },
        { "name": "Other merchandise²", "value": 0 },        
        { "name": "Nonmerchandise receipts³", "value": 304 }        
    ]	
};